- parsely/parselyandroid/ParselyTracker.java
My reading of the android traceback in [this ticket](https://github.com/Parsely/web/issues/7005#issuecomment-344055353) is that there's a `NullPointerException` bubbling out of `ParselyTracker.stopTimerFlush`. I couldn't recreate it. The customer didn't really give me any information other than it's happening most often on Samsung devices and in Android 7. I looked at all the events in datadog from August 10th when the customer reported the problem starting, nothing stood out. I investigated the java.util.Timer class. It looks to me like calling `purge` after calling `cancel` and then setting `this.timer` to `null` is duplicative. Both setting timer to `null` and calling `purge` dereference the queue, timer, and it's tasks so that GC will collect them.  I did find alternative opinions …
> Catch NullPointerException occurring in stopFlushTimer

- ParselyExample/ParselyExample.iml
- ParselyExample/app/app.iml
- ParselyExample/app/build.gradle
- ParselyExample/build.gradle
- ParselyExample/gradle/wrapper/gradle-wrapper.properties
- parsely/parselyandroid/ParselyTracker.java
This should address https://github.com/Parsely/parsely-android/issues/5.
Confirmed working in the ParselyExample app (which has been updated due to that testing).
I should point out there is a possibility, if a track call fires extremely quickly, that the adKey is still null for the first pageview: but it's a consequence of getting the IdInfo in an asynctask, which the Android docs recommend. We could block on getting the ad info, but that seems like a bad solution to me.
I think the rare possibility of one pageview having a different uuid is worth it, considering how hard it was to replicate in code (the adkey get took just a couple hundred milliseconds), but if we really want to ensure that doesn't happen the only other way I can think of other than blocking on that call (which we …
> Use Google Play Services to get the advertising id

- parsely/parselyandroid/ParselyTracker.java
This pull request fixes reported crashes on Android 7 resulting from uncaught `IllegalArgumentException` errors from `getAdvertisingIdInfo`.
> catch IllegalArgumentException from getAdvertisingIdInfo

- parsely/parselyandroid/ParselyTracker.java
After a bunch of fun with getting Android Studio working I've tested this locally in the simulator and it seems to be working fine. This PR is based on a branch that solved the issue in the past here's the [related issue](https://github.com/Parsely/web/issues/7925).
Should resolve: https://github.com/Parsely/web/issues/11252
> Add synchronized keyword to try and stop errors

- parsely/parselyandroid/ParselyTracker.java
This initializes the stored queue as an empty ArrayList rather than nulling it.
Tested in the example app and no errors were visible.
Fixes https://github.com/Parsely/parsely-android/issues/26
> Initialize stored queue rather than setting it to null

- .github/workflows/readme.yml
- example/build.gradle
- example/src/main/AndroidManifest.xml
- example/src/main/java/com/example/MainActivity.java
- example/src/main/res/menu/main.xml
- example/src/main/res/menu/menu_main.xml
- example/src/main/res/values/strings.xml
- example/src/main/res/values/styles.xml
- gradle.properties
- parsely/build.gradle
- parsely/src/main/java/com/parsely/parselyandroid/ParselyMetadata.java
- parsely/src/main/java/com/parsely/parselyandroid/ParselyTracker.java
- parsely/src/main/java/com/parsely/parselyandroid/ParselyVideoMetadata.java
> feat: Use `androidx` namespace

- example/build.gradle
- parsely/build.gradle
- parsely/src/main/java/com/parsely/parselyandroid/ParselyTracker.java
Closes: #45 
This PR updates Jackson (JSON parser) library. The update is forced because of a security flaw of the currently used version ([details](https://ossindex.sonatype.org/vulnerability/CVE-2017-7525?component-type=maven&component-name=org.codehaus.jackson%2Fjackson-mapper-lgpl&utm_source=ossindex-client&utm_medium=integration&utm_content=1.7.0)).
I've taken parsed data after pressing all buttons from top to bottom in the example app, before and after the version bump. See `ParselyTracker#JsonEncode` method.
The diff result is the following:
https://www.diffchecker.com/vtzFPlw2
If I interpret the result correctly the changes are related to:
- timestamp ✅
- order of the parsed objects. But `java.util.HashMap` is already a map that does not respect the order of the values so the …
> fix: bump Jackson to 2.13.3

- example/build.gradle
- parsely/build.gradle
- settings.gradle
This PR is answering the customer request of setting `minSdk` to 21 and `targetSdk` to the currently newest. See internal communication: pd3OIC-mg-p2#comment-153.
I don't see an appropriate suggestion for testing. I've run the `example` app, and it also seems to work fine on API 21.
> Set `minSdk` to 21, `compile` and `target` to 33

- example/src/main/AndroidManifest.xml
- parsely/build.gradle
The library includes the full [Google Mobile Ads SDK](https://developers.google.com/admob/android/quick-start) in order to access the Android Advertising ID (AAID). This causes a crash when including Parse.ly as the Ads library expects to be initialised with an AdMob app ID.
```
java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
******************************************************************************
* The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
* should follow the instructions here:                                       *
* https://googlemobileadssdk.page.link/admob-android-update-manifest         *
* to add a valid App ID inside the AndroidManifest. …
```
> fix: Remove Google Mobile Ads SDK

- parsely/src/main/java/com/parsely/parselyandroid/ParselyTracker.java
This PR tries to address NPE crash that happens in `GetAdKey#onPostExecute`.
Unfortunately, I wasn't able to reproduce the issue, though I think that provided change will address the problem.
In the constructor of `ParselyTracker` we, launch `GetAdKey` AsyncTask which, in its `onPostExecute`, adds `adKey` to `deviceInfo` Map.
But the `deviceInfo` Map is created **after** `GetAdKey` is executed. This makes it possible that `deviceInfo` won't be created before `GetAdKey` tries to use it - hence the NPE.
I wasn't able to reproduce the issue because `GetAdKey#onPostExecute` happens on the main thread, so we have race condition on the main thread, so it's impossible to modify flow via `Thread#sleep`.
As we don't have reproduction, please focus on the code - does the proposed change have some …
> fix: initialize deviceInfo before putting adKey there

- parsely/src/main/java/com/parsely/parselyandroid/ParselyTracker.java
Closes: #57 
This PR addresses the issue reported in #57 by initializing `deviceInfo` synchronously in the constructor of the `ParselyTracker`, rather than waiting for `GetAdKey` async task to complete.
It brings back part of the behavior from before #56 (which introduced the discussed bug) but makes it more explicitly, that initial creation of `deviceInfo` passes `null` for `adKey` property.
1. Checkout `trunk`
2. Apply the PATCH
<details>
<summary>PATCH</summary>
```PATCH
Subject: [PATCH] refactor: move plugins configuration to pluginManagement
---
Index: parsely/src/main/java/com/parsely/parselyandroid/ParselyTracker.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff …
```
> Initialize `deviceInfo` in constructor of `ParselyTracker`

- parsely/src/main/java/com/parsely/parselyandroid/ParselyTracker.java
Closes: #60 
Instead of referencing to the same `Map<String, Object> data` across all events, when updating timestamps of events in `EngagementManager`, we will now create a shallow copy of `data`. This way will stop introducing unwanted changes of data.ts to existing events.
You can see that after the change, each event has its own `data` HashMap so they can update it independently.
| Before | After |
| --- | --- | 
| <img width="492" alt="Screenshot 2023-09-07 at 14 49 44" src="https://github.com/Parsely/parsely-android/assets/5845095/f510125c-0a0a-4d99-92af-a41f7dbd851d"> | <img width="385" alt="Screenshot 2023-09-07 at 14 50 50" src="https://github.com/Parsely/parsely-android/assets/5845095/aae989c6-acd4-45c9-8e6f-fb640cfa06fa"> |
You can see that each event has now its own timestamp …
> Copy `data` map when creating a new heartbeat event

- parsely/src/main/java/com/parsely/parselyandroid/ParselyTracker.java
Closes: #61 
This PR updates time units for `tt` (total time) and `data.ts` (timestamp) parameters. This will match iOS behaviour and was discussed internally here: pd3OIC-1is-p2#comment-313
| Before | After |
| --- | --- | 
| <img width="569" alt="Screenshot 2023-09-07 at 15 50 18" src="https://github.com/Parsely/parsely-android/assets/5845095/c64824d0-d286-486d-9a0e-00f02193150c"> | <img width="572" alt="Screenshot 2023-09-07 at 15 48 21" src="https://github.com/Parsely/parsely-android/assets/5845095/d6e08411-983d-4668-a7b9-713b8ae0f3c6"> |
> Use milliseconds for `ts` and `tt` parameters

- README.md
- publication.gradle
This small PR updates documentation link for the Android SDK and removes `developers` attribute in favor of `organiation` (less prone to changes).
> docs: update README and minor MavenCentral pom file attribute

- parsely/src/main/java/com/parsely/parselyandroid/ParselyTracker.java
This PR contains a set of code quality improvements: removing unneeded checks or making fields `final` when there's no need for them to be mutable. It's not the complete set of improvements I could provide, but I try to limit the size of PRs.
> style: clean-up `ParselyTracker` class

- example/src/main/java/com/example/MainActivity.java
- parsely/src/main/java/com/parsely/parselyandroid/ParselyTracker.java
Closes: #33 
Closes: #69 
This PR allows users to specify `extraData` for engagement sessions. As rightfully noticed by users in tickets, this feature is already documented and in iOS SDK.
| Android | iOS |
| --- | --- | 
| <img width="603" alt="Screenshot 2023-09-14 at 17 57 27" src="https://github.com/Parsely/parsely-android/assets/5845095/aa93ec2e-4a0f-4970-9172-65b228338f6b"> | <img width="568" alt="Screenshot 2023-09-14 at 17 33 49" src="https://github.com/Parsely/parsely-android/assets/5845095/b1f2745d-32ef-4e7b-8f59-f2a3fb5c4882"> |
> feat: allow to add extradata in engagement session

- .github/workflows/readme.yml
- gradle.properties
- parsely/build.gradle
- parsely/src/main/java/com/parsely/parselyandroid/ParselyMetadata.java
- parsely/src/main/java/com/parsely/parselyandroid/ParselyTracker.java
- parsely/src/main/java/com/parsely/parselyandroid/ParselyVideoMetadata.java
Closes #51 
This PR updates convention of code comments from Doxygen (dropped in 1bb51a3) with Javadoc. The main benefit is convenience for library users in terms of viewing documentation for highlighted code. See here:
| Before | After | 
| --- | --- | 
| <img width="1050" alt="Screenshot 2023-09-14 at 19 38 23" src="https://github.com/Parsely/parsely-android/assets/5845095/0fa2e217-5548-4b95-ab3d-09d1218b8188"> | <img width="1002" alt="Screenshot 2023-09-14 at 19 37 31" src="https://github.com/Parsely/parsely-android/assets/5845095/f20323a9-408c-46bd-a707-737d9b61a742"> |
~I decided to not upload `javadoc.jar` as part of the artifact during the release because the source code of the SDK is open, so IDE will get comments directly from the source.~ See …
> docs: ParselyTracker comments to Javadoc style

- .github/workflows/publish.yml
- .github/workflows/readme.yml
- parsely/build.gradle
- publication.gradle
Instead of hardcoding version in repository files.
Closes: #50 
This PR is a small improvement to the release process. Instead of updating a hard-coded version, now the version will be determined by the latest Git tag. It saves a little of overhead and number of actions needed to release a new SDK.
1. Checkout this branch
2. Open `publication.gradle`
3. Comment out content of `signing` extension (no need to test artifacts signing)
4. Add a new tag, e.g. `git tag parsely_testing`
5. Run `./gradlew publishToMavenLocal`
6. Open `~/.m2/repository/com/parsely/parsely/`
7. **Assert you can see directory named `parsely_testing`**
8. Open the directory
9. Open `parsely_testing.pom`
10. **Assert you can see `<version>parsely_testing</version>` tag**
11. Remove the tag (`git tag -d …
> build: get version from the latest tag

- parsely/src/main/java/com/parsely/parselyandroid/ParselyTracker.java
Closes: #28 
This PR is a twin of #73 for `pageview` and `heartbeat` events. It adds a new, internal field `lastPageviewUuid`. See internal discussion about necessity of it: p1696417656257339-slack-C0533SEJ82H
1. Install example app, open logcat
2. Tap on `Track Url`
3. Tap on `Start Engagement`
4. Wait 30 seconds until you see `[Parsely] POST Data {"events": (...)` log. Copy the JSON part.
5. Wait another 30 seconds until another `[Parsely] POST Data {"events": (...)` log, copy it as well.
6. Check the copied logs:
- there should be one ` "action": "pageview"` event, rest of them should be `"action": "heartbeat"`
- every event from both logs should have `"pvid"` field with the same value
<details>
<summary> Click </summary>
</details>
> Add UUID to each pageview event

- .github/workflows/publish.yml
- .github/workflows/readme.yml
- example/src/main/java/com/example/MainActivity.java
- example/src/main/res/layout/activity_main.xml
- example/src/main/res/values/strings.xml
- gradle.properties
- parsely/build.gradle
- parsely/src/main/java/com/parsely/parselyandroid/ParselyTracker.java
Closes: #76 
This PR introduces a new behavior of automatically flushing the events queue using `ProcessLifecycleOwner`. This API is used in e.g. [`AppLifecycleIntegration.kt`](https://github.com/getsentry/sentry-java/blob/main/sentry-android-core/src/main/java/io/sentry/android/core/AppLifecycleIntegration.java#L95) from Sentry Android SDK which works similarly to Parse.ly SDK in the sense of observing application lifecycle.
At the same time, this PR deprecates manual queue flushing.
1. Checkout `main`
2. Install and run example app
3. Tap "track URL"
4. Move app to the background (don't kill)
5. After ~20 seconds, you should see `POST Data {"events":` log
1. Checkout this branch
2. Install and run example app
3. Tap "track URL"
4. Move app to the background (don't kill)
5. See that …
> Send events automatically on application `onStop`

- parsely/build.gradle
- parsely/src/main/java/com/parsely/parselyandroid/ParselyAPIConnection.java
- parsely/src/main/java/com/parsely/parselyandroid/ParselyTracker.java
- parsely/src/test/java/com/parsely/parselyandroid/ParselyAPIConnectionTest.kt
- parsely/src/test/resources/pixel_payload.json
This PR adds unit tests for `ParselyAPIConnection` and adds some minor refactor to it.
Review and running unit tests should be just fine. Due to async nature of, well, `AsyncTask`, you can also verify that each test execution waited for `AsyncTask` to finish. You should see `Pixel request success` or `Pixel request exception` at the end of test logs.
> Add unit tests to `ParselyAPIConnection` and minor refactor of it

- .github/workflows/readme.yml
- parsely/build.gradle
- parsely/src/androidTest/java/com/parsely/parselyandroid/FunctionalTests.kt
- parsely/src/debug/AndroidManifest.xml
- parsely/src/main/java/com/parsely/parselyandroid/ParselyTracker.java
This PR adds a setup for writing and running functional tests on CI. Contrary to unit tests, they are meant to be written via black-box technique. The only mocked/faked element of the setup is API, which is intentionally mocked via MockWebServer.
Additionally, it adds a test case for tracking number of events exceeding maximum number of events that are stored in memory. This asserts correctness of saving/querying data from the local file as well as shows the benefits of functional tests.
Important pivot how to approach the proposed test was made in 8d4a0d39e04b57a6a05bb260e6978e23905c7c12 so please don't pay a lot of attention to implementation details introduced in commit before, which is e97a7a5c3c9ffd2bf75b6b986969e231e021a09a.
Green light on CI should be enough. You can also download …
> Add setup for functional tests. Test sending events over the local variable limit.

- parsely/build.gradle
- parsely/src/androidTest/java/com/parsely/parselyandroid/FunctionalTests.kt
This PR adds a functional test for the scenario described above the test case
Visually, it'll look like this:
https://github.com/Parsely/parsely-android/assets/5845095/729afd64-d18c-488b-b85f-d2adc6b1961f
> Add functional test for validating consumer application `ON_STOP`

- parsely/src/main/java/com/parsely/parselyandroid/AdvertisementIdProvider.kt
- parsely/src/main/java/com/parsely/parselyandroid/ConnectivityStatusProvider.kt
- parsely/src/main/java/com/parsely/parselyandroid/DeviceInfoRepository.kt
- parsely/src/main/java/com/parsely/parselyandroid/EngagementManager.kt
- parsely/src/main/java/com/parsely/parselyandroid/EventsBuilder.java
- parsely/src/main/java/com/parsely/parselyandroid/FlushQueue.kt
- parsely/src/main/java/com/parsely/parselyandroid/InMemoryBuffer.kt
- parsely/src/main/java/com/parsely/parselyandroid/LocalStorageRepository.kt
- parsely/src/main/java/com/parsely/parselyandroid/Logging.kt
- parsely/src/main/java/com/parsely/parselyandroid/ParselyTracker.java
- parsely/src/test/java/com/parsely/parselyandroid/FlushQueueTest.kt
This PR is a set of changes that aim to reduce the size of `ParselyTracker` to reduce the responsibilities of this class and make the transition from Java to Kotlin more readable and easier to review.
I see no need for manual tests of this PR. Unit and functional tests suite should be just fine.
> Prepare `ParselyTracker` for Kotlin migration

- .github/workflows/publish.yml
- .github/workflows/readme.yml
- .github/workflows/submit-gradle-dependencies.yml
This PR:
- moves running functional tests from macOS to Ubuntu runner as KVM is now enabled on Ubuntu. The improvement is significant - from ~13m to ~5m per run
- delegates caching to `gradle-build-action`
- send dependencies on each push because it helps in tracking closed security alerts
- caches AVD files
> ci: use ubuntu-latest for functional tests. Improve CI caching

- example/src/main/java/com/example/MainActivity.java
- parsely/src/androidTest/java/com/parsely/parselyandroid/FunctionalTests.kt
- parsely/src/main/java/com/parsely/parselyandroid/ParselyAlreadyInitializedException.kt
- parsely/src/main/java/com/parsely/parselyandroid/ParselyNotInitializedException.kt
- parsely/src/main/java/com/parsely/parselyandroid/ParselyTracker.kt
- parsely/src/main/java/com/parsely/parselyandroid/ParselyTrackerInternal.kt
- parsely/src/test/java/com/parsely/parselyandroid/ParselyTrackerTest.kt
This PR is addressing 2 review comments from a different PR: https://github.com/Parsely/parsely-android/pull/99#discussion_r1453739601 https://github.com/Parsely/parsely-android/pull/99#discussion_r1453748066
I identify 2 improvement opportunities here:
- confusing SDK initialization and re-initialization problem
- nullability of `sharedInstance()` getter and confusing usage
This PR should address both matters. I'll put details in comments.
No need for manual tests.
> Improve how `ParselyTracker` is accessed

- .github/workflows/readme.yml
- parsely/api/parsely.api
- parsely/build.gradle
- parsely/src/main/java/com/parsely/parselyandroid/ParselyTracker.kt
- settings.gradle
This PR introduces a binary compatibility validator to help reduce risks of introducing unwanted public API change.
Please add or remove a public method from any class and then run `apiCheck` task. It should fail.
> Introduce binary compatibility validator

- parsely/build.gradle
To address [publicly known](https://mvnrepository.com/artifact/com.parsely/parsely/3.1.1) security vulnerabilities
> build: bump jackson databind to `2.14.1`

- example/src/main/java/com/example/InternalDebugOnlyData.java
- example/src/main/java/com/example/MainActivity.java
- parsely/api/parsely.api
- parsely/src/main/java/com/parsely/parselyandroid/ParselyTracker.kt
- parsely/src/main/java/com/parsely/parselyandroid/ParselyTrackerInternal.kt
- parsely/src/test/java/com/parsely/parselyandroid/ParselyTrackerTest.kt
This PR removes some methods from the public API. Those methods are not needed to use the SDK and were making the API less readable. Internal communication: p1706537769574079-slack-C0533SEJ82H
Those methods, although not needed for public API, are useful in the scope of the demo app. That's why I've decided to keep them in `ParselyTrackerInternal` and invoke them using reflection.
Install the `example` app and tap on each button. The app should not crash.
> Remove unneeded methods from api

- example/build.gradle
- parsely/build.gradle
This PR removes unused `appcompat` dependency and bumps `jackson` library to address publicly known vulnerability ([link](https://mvnrepository.com/artifact/com.parsely/parsely/3.1.1)).
> Bump runtime dependencies

- parsely/src/main/resources/META-INF/com/parsely/parsely/verification.properties
Generated during ownership verification. It is not considered a secret.
Build the sdk (`assemble`) and `unzip` generated `.aar` and then `.jar`. The verification file should be under `META-INF/com/parsley/parsely/verification.properties`
> Add Google Play SDK Console verification file
